import { supabase } from '../../supabase.js'
import { requireAdmin, nowIso, normalizePaymentStatus } from '../_shared.js'
const n=v=>Number.isFinite(Number(v))?Number(v):0
async function adjust(items,dir,ref){const touched=[];try{for(const x of items||[]){const id=String(x.id||x.menuId||'');const q=Math.max(0,Math.floor(n(x.qty??x.quantity)));if(!id||!q)continue;const{data:m,error}=await supabase.from('menu_items').select('id,name,stock,pcs_per_mika').eq('id',id).single();if(error)throw error;const next=n(m.stock)+dir*q;if(next<0)throw new Error(`Stok ${m.name} tidak mencukupi`);const{error:up}=await supabase.from('menu_items').update({stock:next,in_stock:next>0,available:next>0,updated_at:nowIso()}).eq('id',id);if(up)throw up;const{error:mv}=await supabase.from('stock_movements').insert({menu_id:id,type:dir<0?'OUT':'IN',quantity_mika:0,pcs_per_mika:m.pcs_per_mika||1,quantity_pcs:q,reference_type:'order',reference_id:ref,description:dir<0?'Penjualan':'Pengembalian stok'});if(mv)throw mv;touched.push({id,q})}}catch(e){for(const t of touched){const{data:m}=await supabase.from('menu_items').select('stock').eq('id',t.id).single();if(m)await supabase.from('menu_items').update({stock:n(m.stock)+t.q,in_stock:true,available:true}).eq('id',t.id)}throw e}}
export default async function handler(req,res){if(!await requireAdmin(req,res))return;try{
 if(req.method==='PATCH'){const{orderId,status,note}=req.body||{};if(!orderId||!status)return res.status(400).json({message:'orderId dan status wajib'});const{data:o,error:re}=await supabase.from('orders').select('*').eq('order_id',orderId).single();if(re)throw re;const cur=o.payment_status||o.status||'pending',next=normalizePaymentStatus(status),was=['paid','processing','completed'].includes(cur),will=['paid','processing','completed'].includes(next);if(!was&&will&&!o.stock_deducted){await adjust(o.items,-1,orderId)}if(was&&!will&&o.stock_deducted){await adjust(o.items,1,orderId)}const{data:u,error:ue}=await supabase.from('orders').update({payment_status:next,stock_deducted:will,note:note??o.note,confirmed_at:next==='paid'?(o.confirmed_at||nowIso()):o.confirmed_at,updated_at:nowIso()}).eq('order_id',orderId).select('*').single();if(ue)throw ue;return res.status(200).json({orderId:u.order_id,paymentStatus:u.payment_status})}
 if(req.method==='POST'){const{customerName,paymentMethod,tableId,items=[]}=req.body||{};if(!items.length)return res.status(400).json({message:'Minimal satu item'});let total=0;const enriched=[];for(const x of items){const{data:m,error}=await supabase.from('menu_items').select('*').eq('id',x.id).single();if(error)throw error;const q=Math.max(1,Math.floor(n(x.qty)));if(n(m.stock)<q)throw new Error(`Stok ${m.name} tidak mencukupi`);const price=n(m.price)+n(x.variantPrice);total+=price*q;enriched.push({id:m.id,name:m.name,qty:q,price,hpp:n(m.hpp),variant:x.variant||'',variantLabel:x.variantLabel||''})}const orderId=crypto.randomUUID();const{error:ie}=await supabase.from('orders').insert({order_id:orderId,customer_name:customerName||'Umum',customer_phone:'',customer_email:'',items:enriched,item_count:enriched.reduce((a,x)=>a+x.qty,0),subtotal:total,total,payment_method:paymentMethod||'CASH',payment_status:'completed',table_id:tableId||null,stock_deducted:false,created_at:nowIso(),updated_at:nowIso()});if(ie)throw ie;await adjust(enriched,-1,orderId);await supabase.from('orders').update({stock_deducted:true}).eq('order_id',orderId);return res.status(200).json({orderId,total,status:'completed'})}
 return res.status(405).json({message:'Method not allowed'})
}catch(e){console.error('[ADMIN ORDERS]',e);res.status(500).json({message:e.message})}}
