import { supabase } from '../../supabase.js'
import { requireAdmin, nowIso, normalizePaymentStatus } from '../_shared.js'
import { reserveOrderStock, releaseOrderStock } from '../_store.js'
const n=v=>Number.isFinite(Number(v))?Number(v):0
const paid=s=>['paid','processing','completed'].includes(String(s||'').toLowerCase())
export default async function handler(req,res){if(!await requireAdmin(req,res))return;try{
 if(req.method==='PATCH'){const{orderId,status,note}=req.body||{};if(!orderId||!status)return res.status(400).json({message:'orderId dan status wajib'});const{data:o,error:re}=await supabase.from('orders').select('*').eq('order_id',orderId).single();if(re)throw re;const cur=normalizePaymentStatus(o.payment_status||o.status),next=normalizePaymentStatus(status);if(cur===next)return res.status(200).json({orderId, paymentStatus:next});if(next==='pending'&&cur!=='pending')return res.status(400).json({message:'Status transaksi yang sudah diproses tidak dapat dikembalikan ke pending.'});if(o.stock_deducted&&!paid(next)){await releaseOrderStock(o)}else if(!o.stock_deducted&&paid(next)){await reserveOrderStock(o)}const{data:u,error:ue}=await supabase.from('orders').update({payment_status:next,stock_deducted:next!=='failed',note:note??o.note,confirmed_at:next==='paid'?(o.confirmed_at||nowIso()):o.confirmed_at,updated_at:nowIso()}).eq('order_id',orderId).select('*').single();if(ue)throw ue;return res.status(200).json({orderId:u.order_id,paymentStatus:u.payment_status})}
 if(req.method==='POST'){const{customerName,paymentMethod,tableId,items=[]}=req.body||{};if(!items.length)return res.status(400).json({message:'Minimal satu item'});let total=0;const enriched=[];for(const x of items){const{data:m,error}=await supabase.from('menu_items').select('*').eq('id',x.id).single();if(error)throw error;const q=Math.max(1,Math.floor(n(x.qty)));if(n(m.stock)<q||m.available===false)throw new Error(`Stok ${m.name} tidak mencukupi`);const price=n(m.price)+n(x.variantPrice);total+=price*q;enriched.push({id:m.id,name:m.name,qty:q,price,basePrice:n(m.price),variant:x.variant||'',variantLabel:x.variantLabel||''})}const orderId=crypto.randomUUID();const order={orderId,items:enriched,stockDeducted:true};await reserveOrderStock(order);try{const{error:ie}=await supabase.from('orders').insert({order_id:orderId,customer_name:customerName||'Umum',customer_phone:'',customer_email:'',items:enriched,item_count:enriched.reduce((a,x)=>a+x.qty,0),subtotal:total,total,payment_method:paymentMethod||'CASH',payment_status:'completed',table_id:tableId||null,stock_deducted:true,created_at:nowIso(),updated_at:nowIso()});if(ie)throw ie}catch(e){await releaseOrderStock(order).catch(()=>{});throw e}return res.status(200).json({orderId,total,status:'completed'})}
 return res.status(405).json({message:'Method not allowed'})
}catch(e){console.error('[ADMIN ORDERS]',e);res.status(500).json({message:e.message||'Gagal memproses transaksi'})}}
