import { supabase } from '../supabase.js'
import { MENU_PLACEHOLDER_IMAGE } from '../../src/data/menuItems.js'
import { nowIso } from './_shared.js'
const MENU_TABLE='menu_items'
const cats=['Makanan','Minuman','Lainnya','Paket']
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v))
function normalizeCategory(v){const s=String(v||'').trim();return cats.includes(s)?s:'Makanan'}
function normalizeVariants(v){return Array.isArray(v)?v.map(x=>({label:String(x?.label||x?.name||'').trim(),price:num(x?.price??x?.additional_price)})).filter(x=>x.label):[]}
function mapRow(r){if(!r)return null;const stock=Math.max(0,num(r.stock));return {id:r.id,name:r.name||'',category:normalizeCategory(r.category),price:num(r.price),stock,pcsPerMika:Math.max(1,num(r.pcs_per_mika,1)),imageUrl:r.image_url||MENU_PLACEHOLDER_IMAGE,imagePath:r.image_path||null,badge:r.badge||'',description:r.description||'',available:r.available!==false&&r.in_stock!==false&&stock>0,inStock:stock>0,hasVariant:Boolean(r.has_variant),variants:normalizeVariants(r.variants),sortOrder:num(r.sort_order),createdAt:r.created_at||nowIso(),updatedAt:r.updated_at||nowIso()}}
function buildRow(item={},existing={}){return {name:String(item.name??existing.name??'').trim(),category:normalizeCategory(item.category??existing.category),price:num(item.price??existing.price),stock:Math.max(0,num(item.stock??existing.stock)),pcs_per_mika:Math.max(1,Math.floor(num(item.pcsPerMika??item.pcs_per_mika??existing.pcs_per_mika,1))),image_url:item.imageUrl??existing.image_url??MENU_PLACEHOLDER_IMAGE,image_path:item.imagePath!==undefined?(item.imagePath||null):(existing.image_path||null),badge:item.badge!==undefined?(item.badge||null):(existing.badge||null),description:item.description!==undefined?(item.description||null):(existing.description||null),available:item.available!==undefined?Boolean(item.available):(existing.available!==false),has_variant:item.hasVariant!==undefined?Boolean(item.hasVariant):Boolean(existing.has_variant),variants:item.variants!==undefined?normalizeVariants(item.variants):normalizeVariants(existing.variants),sort_order:num(item.sortOrder??existing.sort_order),updated_at:nowIso()}}
export async function listMenuItems(activeOnly=false){let query=supabase.from(MENU_TABLE).select('*').order('sort_order').order('created_at');if(activeOnly)query=query.eq('available',true);const {data,error}=await query;if(error)throw new Error(`Gagal memuat menu: ${error.message}`);return clone((data||[]).map(mapRow))}
export async function createMenuItem(item={}){const {data,error}=await supabase.from(MENU_TABLE).insert(buildRow(item)).select('*').single();if(error)throw new Error(`Gagal menambah menu: ${error.message}`);return mapRow(data)}
export async function updateMenuItem(id,item={}){const {data:old,error:r}=await supabase.from(MENU_TABLE).select('*').eq('id',id).maybeSingle();if(r)throw new Error(`Gagal membaca menu: ${r.message}`);if(!old)return null;const {data,error}=await supabase.from(MENU_TABLE).update(buildRow(item,old)).eq('id',id).select('*').single();if(error)throw new Error(`Gagal mengubah menu: ${error.message}`);return mapRow(data)}
export async function deleteMenuItem(id){const {data,error}=await supabase.from(MENU_TABLE).update({available:false,in_stock:false,updated_at:nowIso()}).eq('id',id).select('id').maybeSingle();if(error)throw new Error(`Gagal menonaktifkan menu: ${error.message}`);return {ok:Boolean(data),id}}
export async function uploadMenuImage(base64,name,category){const m=String(base64||'').match(/^data:([^;]+);base64,(.+)$/);if(!m)throw new Error('Format gambar tidak valid');const buffer=Buffer.from(m[2],'base64');const ext=String(m[1].split('/')[1]||'jpg').replace(/[^a-z0-9]/gi,'')||'jpg';const slug=String(name||'menu').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');const path=`${normalizeCategory(category).toLowerCase()}/${slug}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('menu-images').upload(path,buffer,{contentType:m[1],upsert:false});if(error)throw new Error(`Upload gambar gagal: ${error.message}`);return {path,url:supabase.storage.from('menu-images').getPublicUrl(path).data.publicUrl}}
