import React,{useEffect,useState} from 'react'
import AdminPageShell from './AdminPageShell'
import AdminIcon from '../../components/AdminIcon'
import {deleteTable,getTables,saveTable} from '../../lib/adminApi'
import {useLiveRefresh} from '../../lib/liveRefresh'
const QR='https://api.qrserver.com/v1/create-qr-code/?size=360x360&margin=12&data='
const input='w-full rounded-2xl border border-white/70 bg-white/70 px-4 py-3 text-sm font-semibold text-slate-800 shadow-sm outline-none focus:border-rose-300 focus:ring-4 focus:ring-rose-100 dark:border-white/10 dark:bg-white/5 dark:text-white'
export default function AdminTablesPage(){
 const[data,setData]=useState({tables:[]}),[form,setForm]=useState({capacity:4,status:'Kosong'}),[editing,setEditing]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{try{setError('');const r=await getTables();setData({tables:r?.tables||[]})}catch(e){setError(e.message||'Gagal memuat meja.')}}
 useEffect(()=>{load()},[]);useLiveRefresh(load,['tables','orders'],5000)
 const reset=()=>{setEditing(null);setForm({capacity:4,status:'Kosong'})}
 const save=async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await saveTable(editing?{...form,id:editing}:{...form});reset();await load();setNotice(editing?'Meja berhasil diperbarui.':'Meja baru berhasil dibuat.')}catch(e){setError(e.message||'Gagal menyimpan meja.')}finally{setBusy(false)}}
 const remove=async id=>{if(!window.confirm('Hapus meja ini secara permanen? Riwayat transaksi tetap tersimpan, tetapi tidak lagi terhubung ke meja ini.'))return;setBusy(true);setError('');try{await deleteTable(id);if(editing===id)reset();await load();setNotice('Meja berhasil dihapus.')}catch(e){setError(e.message||'Gagal menghapus meja.')}finally{setBusy(false)}}
 const qrUrl=name=>`${QR}${encodeURIComponent(`${window.location.origin}/${name}`)}`
 const copyLink=async table=>{const url=`${window.location.origin}/${table.name}`;try{await navigator.clipboard?.writeText(url);setNotice(`Link ${table.name} berhasil disalin.`)}catch{window.prompt(`Salin link ${table.name}`,url)}}
 const downloadQr=async table=>{const url=qrUrl(table.name);try{const image=new Image();image.crossOrigin='anonymous';image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download=`QR-${table.name}.png`;a.click()};image.onerror=()=>window.open(url,'_blank','noopener,noreferrer');image.src=url}catch{window.open(url,'_blank','noopener,noreferrer')}}
 return <AdminPageShell title="Meja & QR" subtitle="Kode meja otomatis M0001, M0002, dan seterusnya. QR membuka order dengan meja yang terkunci.">
  {error?<div className="mb-4 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>:null}{notice?<div className="mb-4 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{notice}</div>:null}
  <form onSubmit={save} className="mb-5 rounded-[30px] border border-white/70 bg-white/65 p-5 dark:border-white/10 dark:bg-white/5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><label className="flex-1"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">Kapasitas</span><input className={input} type="number" min="1" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></label><label className="flex-1"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">Status</span><select className={input} value={form.status} onChange={e=>setForm({...form,status:e.target.value})} disabled={form.status==='Terisi'}><option>Kosong</option><option>Terisi</option><option>Dipesan</option></select></label><button disabled={busy} className="admin-primary-btn sm:w-auto">{busy?'Menyimpan...':editing?'Simpan Meja':'Tambah Meja'}</button>{editing?<button type="button" onClick={reset} className="admin-secondary-btn sm:w-auto">Batal</button>:null}</div>{editing?<p className="mt-3 text-xs font-semibold text-slate-400">Mengedit <b>{data.tables.find(t=>t.id===editing)?.name}</b>. Nomor meja tidak berubah.</p>:null}</form>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.tables.map(t=><article key={t.id} className="rounded-[26px] border border-white/70 bg-white/65 p-4 shadow-sm dark:border-white/10 dark:bg-white/5"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-black text-slate-900 dark:text-white">{t.name}</p><p className="text-xs text-slate-400">Kapasitas {t.capacity} orang</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${t.status==='Kosong'?'bg-emerald-100 text-emerald-700':t.status==='Terisi'?'bg-rose-100 text-rose-700':'bg-amber-100 text-amber-700'}`}>{t.status}</span></div><div className="mt-4 rounded-2xl border bg-white p-3 text-center"><img src={qrUrl(t.name)} alt={`QR ${t.name}`} className="mx-auto h-44 w-44 rounded-xl" loading="lazy"/><p className="mt-2 break-all text-[10px] font-bold text-slate-500">{window.location.origin}/{t.name}</p></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>downloadQr(t)} className="rounded-xl bg-rose-800 px-3 py-2.5 text-xs font-black text-white">Download QR</button><button type="button" onClick={()=>copyLink(t)} className="rounded-xl border px-3 py-2.5 text-xs font-black">Klik Link</button></div><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setEditing(t.id);setForm({capacity:t.capacity,status:t.status})}} className="rounded-xl border px-3 py-2.5 text-xs font-black">Edit</button><button type="button" onClick={()=>remove(t.id)} className="rounded-xl bg-rose-50 px-3 py-2.5 text-xs font-black text-rose-700">Hapus</button></div></article>)}{!data.tables.length?<div className="col-span-full rounded-[30px] border border-dashed p-10 text-center text-sm font-semibold text-slate-400">Belum ada meja. Tekan “Tambah Meja” untuk membuat M0001 otomatis.</div>:null}</div>
 </AdminPageShell>
}
